name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: window-latest

    steps:
      - name: Checkout
        uses: action/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
